name: Fjelagid
favicon: null
layout_spectrum: 0.24262
typography_spectrum: 0.36297
title: Fjelagið - Stafræn almannatengsl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#336041'
    - '#000000'
    - '#ffffff'
    - '#5d8067'
    - '#8ca594'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
