name: Fjelagid
favicon: null
layout_spectrum: 0.77122
typography_spectrum: 0.36297
title: Fjelagið - Stafræn almannatengsl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#336041'
    - '#000000'
    - '#ffffff'
    - '#5d8067'
    - '#8ca594'
  brandStrength: 0.875
  lightness: 0.7577766813337803
  saturation: 0.8017569782678038
  rhythmicContrast: 0.6267118840478361
purpose: []
